version: "3"

services:
  app:
    container_name: node_app
    restart: always
    image: node:8
    working_dir: /usr/src/app
    volumes: 
      - "./:/usr/src/app/"
    ports:
      - "3000:3000"
    command: "npm start"
    networks: 
      - default
    links:
      - mongo

  mongo:
    container_name: mongo
    image: bitnami/mongodb:latest
    restart: always
    networks: 
      - default
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=root

networks:
  default:
    external: 
      name: node
